import {Location} from './location';
import {Schedule} from './schedule';
import {SocialMedia} from './socialMedia';
import {File} from './file';
export class Store{
    id: string;
    idProvider: string;
    name:string;
    photo:string | undefined;
    cp:string;
	state:string;
	suburb:string;
	street:string;
	externNumber:string;
	internNumber:string | undefined;
    location: Location;
    business:string;
    phone:string;
    email:string;
    description:string;
    nProducts:number;
    images: File[] | undefined;
    Assessment:string[] | undefined;
    score:number;
    Schedule:Schedule | undefined;
	SocialMedia:SocialMedia[] | undefined;
	tags:string[] | undefined;
    createdAt:Date | undefined;
    verifiedAt:Date | undefined;
    modifiedAt:Date | undefined;
    constructor(){
        this.id="";
        this.idProvider="";
        this.name="";
        this.photo=undefined;
        this.cp="";
        this.state="";
        this.suburb="";
        this.street="";
        this.externNumber="";
        this.internNumber=undefined;
        this.location= new Location();
        this.business="";
        this.phone="";
        this.email="";
        this.description="";
        this.nProducts=0;
        this.images= undefined;
        this.Assessment = undefined;
        this.score=0;
        this.Schedule= undefined;
        this.SocialMedia = undefined;
        this.tags = undefined;
        this.createdAt = undefined;
        this.verifiedAt = undefined;
        this.modifiedAt = undefined;
    }
}